### ISSUE TITLE
blade extend

### ISSUE THREAD

**Issue by athashmi** [caffeinated/modules#132]
How can I extend my module view from the view:located at root resources/views folder?

**Comment by kaidesu** [comment]
I assume since you closed this that you figured it out? Extending a layout from the root app is the same - so if you have `resources/views/layouts/default.blade.php` you would simply extend `layouts.default` in your module's view file.

If however, you wish to extend a layout you have with your module, you'll need to reference the module slug as the namespace: `blog::layouts.default`.

**Comment by athashmi** [comment]
yup exactly, It was my fault. thanks anyway for explanation.

**Comment by athashmi** [comment]
yup, I figured it out then, thanks anyway for explanation.

**Comment by kaidesu** [comment]
:+1:
