### ISSUE TITLE
Nothing to Migrate

### ISSUE THREAD

**Issue by mitajunior** [caffeinated/modules#148]
app->modules->module-name->Database->Migrations->create_users_table.php

composer dumpautoload

php artisan module:migrate module-name

[nothing to migrate]

Why is it not seeing the migrations in my modules?

**Comment by kaidesu** [comment]
Is your module enabled?

**Comment by mitajunior** [comment]
yeah it is

**Comment by cyrilmarois** [comment]
I got the same on ubuntu (14.04) but it works in local (mac OSX 10.11.14).

**Comment by shanecp** [comment]
This happens if your `slug` differs from the name of the module's folder.

I had my slug as `hr` and the module folder as `HumanResources`. Then I renamed the slug to `human-resources` to make it work.

I think it would be better to make the slug independent from folder name and the namespace.

After you change the folder, run `php artisan module:optimize`.

**Comment by cyrilmarois** [comment]
@shanecp yes i agree, and thanks
@mitajunior I solved it recreating my module the following way
<pre>
<code>
php artisan make:module modulename
</code>
</pre>

Note the name is full lowercase, then I left, module, slug and namespaces as suggested by the application.

Hope it helps
