### ISSUE TITLE
no module created

### ISSUE THREAD

**Issue by almaweb** [caffeinated/modules#16]
Mybe I miss some things, but when i create a module..nothing is created...even i have message that module was created.....when i list module...nothing is listed...

**Comment by kaidesu** [comment]
Were you trying to use the `module:list` Artisan command and it wasn't showing anything? There was a misnamed configuration key that was probably causing this. I fixed it today, so update your modules package and give it a try again.

The module should have been created regardless though - check your file system inside your app directory.

Otherwise, I'll need more information to go off of to help fix this.

**Comment by almaweb** [comment]
Whene I use module:list it give me that they are no module....I tiried a fresh install of laravel, but hte same result....

**Comment by almaweb** [comment]
Sorry..But now all is ok...I have module created...

**Comment by kaidesu** [comment]
Glad everything is working for you!
