### ISSUE TITLE
Missing translation throws an error

### ISSUE THREAD

**Issue by Goldenblum** [caffeinated/modules#166]
Hello,

I recently upgraded from Laravel 5.1 to 5.2 and as far as I noticed the modules package runs fine except one little and annoying issue:

My language files are located at \app\Modules\News\Resources\Lang\ro\admin.php for example and I'm calling them from my blade view using usual trans('news::admin.line'). Everything works fine except from the case when the translation is not found and then it throws this error:

ErrorException in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\refillio\vendor\laravel\framework\src\Illuminate\Translation\FileLoader.php line 88:
Argument 1 passed to Illuminate\Translation\FileLoader::loadNamespaceOverrides() must be of the type array, integer given, called in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\refillio\vendor\laravel\framework\src\Illuminate\Translation\FileLoader.php on line 73 and defined (View: C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\refillio\public\themes\refillio\views\modules\news\admin\addNews.blade.php)

Previously, if a translation was not found, blade was showing the variable name instead.

Any ideas what can cause this error?

Regards,
Dan

**Comment by kaidesu** [comment]
Hmm, seems the way translation files should be loaded has changed. This may be the cause of the issue you're running into (I haven't tested though).

Instead of using `Lang::addNamespace()`, create a `boot` method and add the following (be sure to update the paths accordingly):

```php
$this->loadTranslationsFrom(__DIR__.'/path/to/translations', 'moduleslug');
```

I'll be sure to update the package for this so any future modules will be set up properly automatically.

---

For future reference and debugging tips, anything documented under [Package Development](https://laravel.com/docs/5.2/packages) in the Laravel documentation applies to modules.

**Comment by Goldenblum** [comment]
Hi,

Thank you for your fast reply. I run a composer update today and laravel framework upgraded from 5.2.24 to 5.2.25 and the problem vanished. It might have been a framework little bug that now got corrected.
Thank you again for your help.

Regards,
Dan
