### ISSUE TITLE
Add Event classes for various commands

### ISSUE THREAD

**Issue by VizuaaLOG** [caffeinated/modules#182]
Loving this package so far, and has organised my project is a much more maintainable way. An idea I had for this package, is that if a onEnabled method could be added, it would only be called when a module is enabled. Not sure if this would be a good fit for the service provider or not, or whether it would require a custom wrapper class.

The idea is that a module may need to make changes to a database table, set it self up, instead of doing this each time the module is loaded, like in the register part the service provider, it would only be called when a module is enabled.

Maybe also an opposite, onDisabled, to cleanup the module. e.g. clear its cache etc.

**Comment by kaidesu** [comment]
Event firing would be a nice addition for sure. I'll keep this open for when I can fit it in a future update.

**Comment by sroutier** [comment]
Hello,

I created something like this in my fork that you can see at https://github.com/sroutier/l51esk-modules.
It's not based on an event system, but instead when the Modules::enable() is called it will trigger the matching enable() function in the module itself. Same goes for the disable command. To support this a new Maintenance class is created from a stub for each module.
I also added the concept of having a module initialize and uninitialize because of my requirements. The idea is that the initialize command prepares everything as needed (ie: set the DB, etc.) but leaves the module disabled, then the admin/user can enable or disable it with minimal impact, the uninitialize command cleans up everything.

If you are interested in my implementation I can create a PR, let me know.
You can see the code change here: https://github.com/sroutier/l51esk-modules/commit/e21d01e83502b62e28f24f089c6954104ac9ee99

Cheers, and thanks for your project, it helps a lot.
/S

**Comment by VizuaaLOG** [comment]
Been thinking about this, and not sure if using Laravel's events implementation would work. The event would be fired but thinking about it I'm not sure if a newly enabled module would pick up the fired event. Might have a look into this and see how it goes.

I do quite like @sroutier 's implementation. As it would only be called when a module is enabled or disabled, the overhead of loading the module wouldn't really matter all that much.
