### ISSUE TITLE
Module seed not working

### ISSUE THREAD

**Issue by HWilliamRS** [caffeinated/modules#318]
Module seed not working

Hello,  I was wondering why when I run the  '**php artisan module:seed content**' the seeder doesn’t execute and  I gives me nothing back as feedback,  am I missing something?

I already ran:
**composer-dumpautoload**
**php artisan optimize**

Here is my code:

```
<?php

use Illuminate\Database\Seeder;

class ContentDatabaseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $this->call(PostsTableSeeder::class);
    }
}
```
I’ve read a lot in similar issues but I think there is a possibility that something have changed . Related issues: [#245](https://github.com/caffeinated/modules/issues/245)    [#227](https://github.com/caffeinated/modules/issues/227)    [#272](https://github.com/caffeinated/modules/issues/272) .

**Comment by d8vjork** [comment]
Yep, still not working, I'm testing the SeedModule command and I think its a problem with autoload (because it cannot load Database classes in Modules)

**Comment by rutvij2292** [comment]
Any updates on `module:seed`

**Comment by rutvij2292** [comment]
I tried this solution temporarily.

I created ModuleNameSeeder.php file inside `\App\Modules\ModuleName\Database\Seeds\` directory.

```
<?php

namespace App\Modules\[ModuleName]\Database\Seeds;

use Illuminate\Database\Seeder;

class ModuleNameSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $this->call(OtherSeeder::class);
    }
}
```

I have OtherSeeder file in the same directory. 

Instead of running `php artisan module:seed [SLUG]` 

run this COMMAND: `php artisan db:seed --class=\App\Modules\ModuleName\Database\Seeds\ModuleNameSeeder`


If anyone has a better solution please let me know. Thanks in advance for this wonderful and helpful plugins. :)

**Comment by d8vjork** [comment]
You an with module:seed command, but need rename the seeder class with {ModuleName}DatabaseSeeder.

De: Rutvij Kothari<mailto:notifications@github.com>
Enviado: sábado, 29 de julio de 2017 8:58
Para: caffeinated/modules<mailto:modules@noreply.github.com>
CC: D8vjörk<mailto:d8vjork@outlook.com>; Comment<mailto:comment@noreply.github.com>
Asunto: Re: [caffeinated/modules] Module seed not working (#318)


I tried this solution temporarily.

I created ModuleNameSeeder.php file inside \App\Modules\ModuleName\Database\Seeds\ directory.

<?php

namespace App\Modules\[ModuleName]\Database\Seeds;

use Illuminate\Database\Seeder;

class ModuleNameSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $this->call(OtherSeeder::class);
    }
}


I have OtherSeeder file in the same directory.

Instead of running php artisan module:seed [SLUG]

run this COMMAND: php artisan db:seed --class=\App\Modules\ModuleName\Database\Seeds\ModuleNameSeeder

If anyone has a better solution please let me know. Thanks in advance for this wonderful and helpful plugins. :)

**Comment by rutvij2292** [comment]
Thanks @d8vjork. It works. 👍
