### ISSUE TITLE
Laravel 5.6 support

### ISSUE THREAD

**Issue by appdezign** [caffeinated/modules#347]
When I try to upgrade to Laravel 5.6, I get an error because of a dependency in caffeinated/modules:

`
"require": {
        "illuminate/support": "5.5.*"
    },
`

**Comment by A-Lawrence** [comment]
That's because this package hasn't yet been updated to use Laravel 5.6.  As such, it'll keep rejecting the package's requirement for only Laravel 5.5 framework elements.

If @kaidesu doesn't manage to beat me to it, I'll try and get a PR submitted sometime this week (off the top of my head, there's minimal impact for a 5.6 upgrade).

**Comment by appdezign** [comment]
That would be great, thanks.

**Comment by robinhalet** [comment]
Any news for 5.6 support ?

**Comment by nikocraft** [comment]
Anynews?

**Comment by kaidesu** [comment]
v4.3 has been pushed 👍
