### ISSUE TITLE
Question: nWidart/laravel-modules vs caffeinated/modules

### ISSUE THREAD

**Issue by Nowi5** [caffeinated/modules#365]
Hi Community,

with the recent hours and even days I'm looking for a good start for a large application with a modular concept and multi tenant (SaaS)(https://github.com/hyn/multi-tenant). So I located the both packages nWidart/laravel-modules & caffeinated/modules, which looks somehow similar. nWidart has some more github stars, but any additional features (e.g. more stable, works with multi tenants,...) compared to caffeinated?

Thank you for your support.

**Comment by Nowi5** [comment]
https://github.com/caffeinated/modules/issues/365

**Comment by illuminate3** [comment]
Personally I prefer caffienated. However, at the moment, I have problems with getting config files to publish for 5.6 laravel. 

Have you tried both yet?

**Comment by Nowi5** [comment]
No I haven't, I just collect information for a bigger project, >20 modules, 10-20 tenants each 250-150.000 user total. So I need something with a quick support and which is easy to adapt. Using Laravel 5.6. Why to you prefer caffeinated, is it lighter or more flexible? I'm not impressed by the community yet. Seems that Pull requests takes very long.

**Comment by illuminate3** [comment]
Code review is subjective but I like how caffinated sticks with laravel progression. At one time, this place used to be quick.

nWidart is based off ping-pong modules and is heavily based on Laravel 5.0. However, nWidart keeps on top of things and has really moved his port forward a lot. I am having troubles with things like mergeconfig. However, it works and that is what I needed to move to while waiting for the publish:config gets fixed in caffinated. I will more than likely back port. To be honest, I'm a bit of caffinated fan boi.

I didn't use hyn when I built a multi-tenancy app with Laravel 5.1 (back then) since it was still beta. I used my own solution since I wanted a single database but multi-site. However, if not mistake,  multi-tenancy should work with either of these module systems.

You should check out the orchestra platform (http://orchestraplatform.com/) however, I don't think it has been updated to 5.6 but I might be wrong. It has the tenancy and it's own module system. That developer is now involved with the Laravel core if not mistaken.
