### ISSUE TITLE
migration-reset ordering

### ISSUE THREAD

**Issue by mouhsinelonly** [caffeinated/modules#63]
running php artisan moudle:migrate-reset starts from older to newer when the correct scenarion is from newer migrations to older ones.

also running php artisan module:migrate should respect the ordering set in module.json ,because some modules might have primary keys pointing to others.

**Comment by kaidesu** [comment]
Fixed in https://github.com/caffeinated/modules/commit/255a63b18c2a2d5522937014d5ea32954ef4002a and https://github.com/caffeinated/modules/commit/1d370ab368f87258840b587852b94b42a60a4838. The package will now only take enabled modules into consideration when running these commands as well (rather than ALL modules, regardless if they were set to enabled or disabled).
